#!/usr/bin/env php
<?php

$GLOBALS["BOLDGREEN"] = "\x1b[1m\x1b[32m";
$GLOBALS["WHITE"] = "\x1b[97m";
$GLOBALS["BOLDWHITE"] = "\x1b[1m\x1b[97m";
$GLOBALS["BOLDCYAN"] = "\x1b[1m\x1b[36m";
$GLOBALS["CYAN"] = "\x1b[36m";
$GLOBALS["RED"] = "\033[31m";
$GLOBALS["BOLDRED"] = "\x1b[1m\x1b[31m";
$GLOBALS["BLUE"] = "\x1b[34m";


$GLOBALS["RESET"] = "\x1b[0m";

function show_help(array $argv) {
    echo <<< EOL
    Database management tool

    {$GLOBALS["BOLDGREEN"]}Usage: {$GLOBALS["BOLDCYAN"]}$argv[0] [OPTIONS] [FILE] 

    {$GLOBALS["BOLDGREEN"]}Options: 
        {$GLOBALS["BOLDCYAN"]}-r{$GLOBALS["WHITE"]},{$GLOBALS["BOLDCYAN"]}--remove  <INPUT_JSON>        {$GLOBALS["WHITE"]}JSON to database (replace)
        {$GLOBALS["BOLDCYAN"]}-a{$GLOBALS["WHITE"]},{$GLOBALS["BOLDCYAN"]}--add     <INPUT_JSON>        {$GLOBALS["WHITE"]}JSON to database (add)
        {$GLOBALS["BOLDCYAN"]}-x{$GLOBALS["WHITE"]},{$GLOBALS["BOLDCYAN"]}--export  <OUTPUT_JSON>       {$GLOBALS["WHITE"]}Database to JSON    
    EOL;
   
   die;
}

function error($argv) {
    $filename = __FILE__;
    $padding = str_repeat(" ", strlen($argv[0] . $argv[1]));
    echo <<< EOL
    {$GLOBALS["BOLDRED"]}error[418]{$GLOBALS["WHITE"]}: Missing JSON file after {$argv[1]} option
    {$GLOBALS["BLUE"]} --> {$GLOBALS["WHITE"]}{$filename}
     {$GLOBALS["BLUE"]} |
    {$GLOBALS["BLUE"]}  |    {$argv[0]} {$argv[1]}
    {$GLOBALS["BLUE"]}  |    {$padding}{$GLOBALS["BOLDRED"]}  ^ Missing filename here

    {$GLOBALS["BOLDRED"]}error{$GLOBALS["WHITE"]}: could not run the file due to previous error 

    EOL;
    die;
}




if(!isset($argv[1])) {
    show_help($argv);
}

$servername = "localhost";
$username = "root";
$password = "root";
$dbname = "sae23";

$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn -> connect_error) {
    die("Connection failed: " . $conn -> connect_error);
}




switch ($argv[1]) {
    case "-h":
    case "--help":
        show_help($argv);
        break;

    case "-r":
        if(!isset($argv[2])) {
            error($argv);
        }

        $json_file = $argv[2];
        $jsonData = file_get_contents($json_file);
        $array = json_decode($jsonData, true);

        $tables = [
            "deplacements",
            "emploidutemps",
            "equipages",
            "lieus",
            "personal_access_tokens",
            "rejoints",
            "utilisateurs",
            "vehicules",
        ];

        foreach($tables as $table) {
            $sql = "DELETE FROM $table";
            if ($conn -> query($sql) !== true) {
                echo "Error: " . $sql . "<br>" . $conn -> error;
            }
        }

        foreach ($array as $tableName => $tableRows) {
            foreach ($tableRows as $row) {
                $columns = implode(", ", array_keys($row));
                $values = "'" . implode("', '", array_values($row)) . "'";
                $values = str_replace("''", "null", $values);
                $sql = "INSERT INTO $tableName ($columns) VALUES ($values)";

                if ($conn -> query($sql) !== true) {
                    echo "Error: " . $sql . "<br>" . $conn->error;
                }
            }
        }

        echo $GLOBALS["BOLDCYAN"] . "[+]"  . $GLOBALS["BOLDWHITE"] . "Data import successfully";
        $conn -> close();
        break;

    case "-a":
    case "--add":
        if(!isset($argv[2])) {
             error($argv);
        }
     
        $json_file = $argv[2];
        $jsonData = file_get_contents($json_file);
        $array = json_decode($jsonData, true);

        foreach ($array as $tableName => $tableRows) {
            foreach ($tableRows as $row) {
                $columns = implode(", ", array_keys($row));
                $values = "'" . implode("', '", array_values($row)) . "'";
                $sql = "INSERT INTO $tableName ($columns) VALUES ($values)";

                if ($conn->query($sql) !== true) {
                    echo "Error: " . $sql . "<br>" . $conn->error;
                }
            }
        }

        echo $GLOBALS["BOLDCYAN"] . "[+]"  . $GLOBALS["BOLDWHITE"] . "Data import successfully";
        $conn -> close();
        break;


    case "-x":
    case "--export":
        if(!isset($argv[2])) {
            error($argv);
        }

        $tables = [
            "deplacements",
            "emploidutemps",
            "equipages",
            "lieus",
            "personal_access_tokens",
            "rejoints",
            "utilisateurs",
            "vehicules",
        ];

        $data = [];

        foreach ($tables as $table) {
            $sql = "SELECT * FROM $table";
            $result = $conn->query($sql);

            if ($result->num_rows > 0) {
                while ($row = $result->fetch_assoc()) {
                    $data[$table][] = $row;
                }
            }
        }

        $jsonData = json_encode($data, JSON_PRETTY_PRINT);

        file_put_contents($argv[2], $jsonData);
        $conn -> close();

        echo $GLOBALS["BOLDCYAN"] . "[+]"  . $GLOBALS["BOLDWHITE"] . "Data exported successfully";

        break;
}

